#
# @docker-compose Copyright (c) 2022 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#
  

version: '3.8'
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: converter_db
    ports:
      - "3308:3306"
    expose:
      - "3308"
    network_mode: bridge 


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    expose:
      - "8080"
    network_mode: bridge 
    links: 
      - db


  convfrontend:
    container_name: convfrontend
    image: conv_frontend
    build:
      context: .
      dockerfile: AT19_FRONTEND_CONVERT/dockerfile
    ports:
      - "5017:5017"
    network_mode: bridge 
      

  convbackend:
    container_name: convbackend
    image: conv_backend
    build:
      context: .
      dockerfile: AT19_CONVERTER/dockerfile
    ports:
      - "5000:5000"
    network_mode: bridge 
    depends_on:
      - db 
  

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    expose:
      - "27017"
    network_mode: bridge
  

  mongoadmin:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://127.0.0.1:27017/
    network_mode: bridge
    links:
      - mongodb
    

  mlfrontend:
    container_name: mlfrontend
    image: ml_frontend
    build:
      context: .
      dockerfile: AT19_FRONTEND/dockerfile
    ports:
      - "8000:8000"
    network_mode: bridge
 
 
  mlbackend:
    container_name: mlbackend
    image: ml_backend
    build:
      context: .
      dockerfile: AT19_MACHINE_LEARNING/dockerfile
    ports:
      - "5001:5001"
    network_mode: bridge 
    depends_on:
      - mongodb




